# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Projects"
  url = "project"
  weight = 20

[[main]]
  parent = "Projects"
  name = "Current"
  url = "project"
  weight = 10
[[main]]
  parent = "Projects"
  name = "Finished"
  url = "project_finished"
  weight = 20

#[[main]]
#  name = "Topics"
#  url = "topics"
#  weight = 30

[[main]]
  name = "People"
  url = "#people"
  weight = 40

[[main]]
  name = "Publications"
  url = "publication"
  weight = 50

[[main]]
  name = "Teaching"
  url = "teaching"
  weight = 70
  
[[main]]
  name = "SMS"
  url = "sms"
  weight = 80

[[main]]
  name = "News"
  url = "news"
  weight = 85
  
[[main]]
  name = "Contact"
  url = "contact"
  weight = 90
